### ISSUE TITLE
Setup.py depends indirectly on Django

### ISSUE THREAD

**Issue by domsekotill** [gintas/django-picklefield#44] opened 2019-08-30 20:42 UTC
[This commit](https://github.com/gintas/django-picklefield/commit/7dcef232808bc88a653088df84aaa32e44da19f7#diff-2eeaed663bd0d25b7e608891384b7298) causes installation from source to fail if Django is not already installed when *setup.py* is called. (For instance when attempting to install all project packages in one go to a clean environment like a container or virtualenv.)

**Is `VERSION` necessary? If not then `__version__` can just be a string constant which is much easier to read.**

Otherwise, ugly as it may be, could I suggest the following; it depends only on packages that will be present if setuptools is installed, which is *reasonably* likely in a clean environment, unlike Django:

```python
from pkg_resources import packaging

VERSION = (2, 0, 0, 'alpha', 0)
__version__ = str(packaging.version.Version('.'.join(str(p) for p in VERSION)))
```

**Comment by twidi** [comment] 2019-12-19 14:22
Also, using `get_version` from django with `alpha` , will call a subprocess `git log...` in django that will try to get the timestamp of the git head... of django, not of picklefield

Even when deployed without git.

And last point, tjhe package is published as `2.0` so we should not have this `alpha` here.

**Comment by antnieszka** [comment] 2020-04-24 18:48
I have the same problem with fresh project installation:
```
Collecting django-picklefield==2.0
  Using cached django-picklefield-2.0.tar.gz (10 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/aga/Projects/ki-site/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-dnl9cqzg/django-picklefield/setup.py'"'"'; __file__='"'"'/tmp/pip-install-dnl9cqzg/django-picklefield/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-dnl9cqzg/django-picklefield/pip-egg-info
         cwd: /tmp/pip-install-dnl9cqzg/django-picklefield/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-dnl9cqzg/django-picklefield/setup.py", line 5, in <module>
        import picklefield
      File "/tmp/pip-install-dnl9cqzg/django-picklefield/picklefield/__init__.py", line 3, in <module>
        import django.utils.version
    ModuleNotFoundError: No module named 'django'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by charettes** [comment] 2024-04-04 15:29
Closing as duplicate of #56.

**Closed by charettes** 2024-04-04 15:29 UTC
